// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA3qoKg87CWa259MVkMmveksjzEZfrGg4',
    appId: '1:1073957560927:web:173988435b8cec122431ea',
    messagingSenderId: '1073957560927',
    projectId: 'iotsmarthome-187be',
    authDomain: 'iotsmarthome-187be.firebaseapp.com',
    storageBucket: 'iotsmarthome-187be.firebasestorage.app',
    measurementId: 'G-J1JFQFEQWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-8roIYontq-5npve6KB1MKJn3nPwKyAs',
    appId: '1:1073957560927:android:e1ceb2a3c380e47f2431ea',
    messagingSenderId: '1073957560927',
    projectId: 'iotsmarthome-187be',
    storageBucket: 'iotsmarthome-187be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjj3kwvX-zo-CvRbp-7Y2SxgYfC5GcstI',
    appId: '1:1073957560927:ios:6beb447245cbab702431ea',
    messagingSenderId: '1073957560927',
    projectId: 'iotsmarthome-187be',
    storageBucket: 'iotsmarthome-187be.firebasestorage.app',
    iosBundleId: 'com.example.iotSmarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjj3kwvX-zo-CvRbp-7Y2SxgYfC5GcstI',
    appId: '1:1073957560927:ios:6beb447245cbab702431ea',
    messagingSenderId: '1073957560927',
    projectId: 'iotsmarthome-187be',
    storageBucket: 'iotsmarthome-187be.firebasestorage.app',
    iosBundleId: 'com.example.iotSmarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA3qoKg87CWa259MVkMmveksjzEZfrGg4',
    appId: '1:1073957560927:web:8c5798350b09880a2431ea',
    messagingSenderId: '1073957560927',
    projectId: 'iotsmarthome-187be',
    authDomain: 'iotsmarthome-187be.firebaseapp.com',
    storageBucket: 'iotsmarthome-187be.firebasestorage.app',
    measurementId: 'G-72JGSQG5R6',
  );
}
